#!/bin/sh

# Load

module="led"
device="led"
mode="664"

insmod ./$module.ko $* || exit 1

if grep -q '^staff:' /etc/group; then
	group="staff"
else
	group="wheel"
fi

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

rm -f /dev/${device}
mknod /dev/${device} c $major 0
chgrp ${group} /dev/${device}
chmod ${mode} /dev/${device}

# Check
echo CHECK
echo
echo 'cat /proc/devices | grep led'
cat /proc/devices | grep led
echo 'ls -l /dev/led'
ls -l /dev/led
