#!/bin/sh

module="scull"
device="scull"
mode="664"

make
insmod ./$module.ko $* || exit 1

if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

rm -f /dev/${device}[0-3]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
chgrp $group /dev/${device}[0-3]

rm -f /dev/${device}_single
mknod /dev/${device}_single c $major 4
chgrp $group /dev/${device}_single
chmod $mode /dev/${device}_single

rm -f /dev/${device}_uid
mknod /dev/${device}_uid c $major 5
chgrp $group /dev/${device}_uid
chmod $mode /dev/${device}_uid

rm -f /dev/${device}_wuid
mknod /dev/${device}_wuid c $major 6
chgrp $group /dev/${device}_wuid
chmod $mode /dev/${device}_wuid

rm -f /dev/${device}_priv
mknod /dev/${device}_priv c $major 7
chgrp $group /dev/${device}_priv
chmod $mode /dev/${device}_priv
