#!/bin/sh

echo 'cat /proc/devices | grep scullc'
cat /proc/devices | grep scullc

devfiles=$(ls -l /dev/scullc*)

echo
echo 'Hello'

if [ -n "$devfiles" ]; then
	echo
	echo 'scullc devices:'
	ls -al /dev/scullc*
else
	echo
	echo "/dev/scullc* don't exist"
fi

echo
echo 'cat /proc/scullc_proc'
cat /proc/scullc_proc
